version: '3'
services:
  ### AWS services emulator
  aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3:5000,sqs:5001,sns:5002
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localhost
      - LOCALSTACK_HOSTNAME=localhost
    ports:
      - "5000-5002:5000-5002"
      - "8080:8080"
    network_mode: "host"
  
  ### Redis Service 
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: "host"
  
  ### Document generator service
  stream-v:
    build: ./stream
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Microservice #1
  extract-text-v:
    build: ./services/extract-text
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Microservice #2
  extract-images-v:
    build: ./services/extract-images
    network_mode: "host"
    environment: 
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1