version: '3'
services:
  ### AWS services emulator
  aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3:5000,sqs:5001,sns:5002
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=localhost
      - LOCALSTACK_HOSTNAME=localhost
    ports:
      - "5000-5002:5000-5002"
      - "8080:8080"
    network_mode: "host"
  
  ### Redis Service 
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: "host"
  
  ### Document generator service
  stream-v:
    build: ./stream
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Microservice #1
  extract-text-v:
    build: ./services/extract-text
    network_mode: "host"
    environment:
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Microservice #2
  extract-image-preview-v:
    build: ./services/extract-image-preview
    network_mode: "host"
    environment: 
      AWS_ACCESS_KEY_ID: random
      AWS_SECRET_ACCESS_KEY: random
      AWS_REGION: us-east-1

  ### Java based services
  # process-file-stream-text:
  #   image: process-file-stream
  #   network_mode: "host"
  #   environment:
  #     AWS_ACCESS_KEY_ID: random
  #     AWS_SECRET_ACCESS_KEY: random
  #     AWS_REGION: us-east-1
  #     PROCESS_QUEUE_NAME: file-stream-text
  #     SPRING_PROFILES_ACTIVE: extract-text
  #     PORT: 8081
  
  # process-file-stream-preview-images:
  #   image: process-file-stream
  #   network_mode: "host"
  #   environment:
  #     AWS_ACCESS_KEY_ID: random
  #     AWS_SECRET_ACCESS_KEY: random
  #     AWS_REGION: us-east-1
  #     PROCESS_QUEUE_NAME: file-stream-image-preview
  #     SPRING_PROFILES_ACTIVE: extract-image-preview
  #     PORT: 8082
